version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: medai_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MedAi_isthebest
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: medai_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql://postgres:MedAi_isthebest@db:5432/postgres
      - GROQ_API_KEY
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: medai_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
